config/routes.rb
Rails.application.routes.draw do
  resources :items do
    put '/move', to: 'items#move', as: :move, on: :member
    put '/move-all', to: 'items#move_all', as: :move_all, on: :member
  end
  get '/warehouse/:name', to: 'items#warehouse', as: :warehouse
  delete '/warehouse/:name', to: 'items#close_warehouse'
  root to: 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord


  def collapse
    self.reload
    @items = Item.where(name: name, warehouse: warehouse)

    # Aquí unificamos el stock de todos los items

    @items.where.not(id: self.id).delete_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    redirect_to items_path, flash: {success: 'Item was successfully created.'}
  end

  def update
    redirect_to items_path, flash: {success: 'Item was successfully updated.'}
  end

  def destroy
    @item.destroy
    redirect_to items_path, flash: {success: 'Item was successfully destroyed.'}
  end

  def warehouse
    @name = params[:name]
  end

  def move
    redirect_to items_path, flash: { success: 'Item moved successfully' }
  end

  def move_all
    redirect_to items_path, flash: { success: 'Items moved successfully' }
  end

  def close_warehouse
    @name = params[:name]
    redirect_to items_path, flash: { success: "Warehouse #{@name} closed" }
  end

  private
    def set_item
      @item = Item.new
    end

    def item_params
      params.require(:item).permit(:name, :description, :warehouse, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when "notice" then "alert alert-info alert-dismissible fade show"
        when "success" then "alert alert-success alert-dismissible fade show"
        when "error" then "alert alert-danger alert-dismissible fade show"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.row
  .col-12.col-md-6.offset-md-3
    .card.mt-4.mb-4
      .card-header
        %h2.text-center=title
      .card-body
        = render partial: 'model_errors', locals: { item: @item }
        = form_for @item do |f|
          .form-group
            = f.label :name
            = f.text_field :name, class: 'form-control'
          .form-group
            = f.label :description
            = f.text_area :description, class: 'form-control'
          .form-group
            = f.label :warehouse
            = f.text_field :warehouse, class: 'form-control'
            .small.text-muted Name of the warehouse where it's stored
          .form-group
            = f.label :stock
            = f.number_field :stock, class: 'form-control'
            .small.text-muted How many items in this warehouse
          .form-group
            = f.submit 'Save', class: 'btn btn-primary'
            = link_to 'Back', root_path, class: 'btn btn-light'

app/views/items/_item.html.haml
= link_to item, class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center' do
  = "#{item.name} (#{item.warehouse})"
  %span.badge.badge-primary.badge-pill=item.stock

app/views/items/_item_details.html.haml
.card.mb-4.mt-4
  .card-header
    %h3=item.name
  .card-body
    %p=item.description
    .text-muted
      %b=item.stock
      units in
      %b
        =link_to item.warehouse, warehouse_path(item.warehouse)
      warehouse
  .card-footer
    = link_to 'Edit', edit_item_path(item), class: 'card-link'
    = link_to 'Delete', item, method: 'delete', class: 'card-link', data: { confirm: 'Are you sure?' }

app/views/items/_move_all_form.html.haml
.card.mb-4.mt-4
  .card-header
    %h3 Move all to warehouse
  .card-body
    = form_tag move_all_item_path(item), method: 'put' do
      .form-group
        = text_field_tag "warehouse", "", placeholder: "New warehouse name", class: "form-control"
      .form-group
        = submit_tag "Move", class: "btn btn-primary"

app/views/items/_move_form.html.haml
.card.mb-4.mt-4
  .card-header
    %h3 Move items to warehouse
  .card-body
    = form_tag move_item_path(item), method: 'put' do
      .form-group
        = text_field_tag "warehouse", "", placeholder: "New warehouse name", class: "form-control"
      .form-group
        = number_field_tag "units", "", placeholder: "Number of units to move", class: "form-control"
      .form-group
        = submit_tag "Move", class: "btn btn-primary"

app/views/items/edit.html.haml
- if @item
  = render partial: 'form', locals: { title: 'New item'}

app/views/items/index.html.haml
%h1.text-center.mt-4.mb-4 All items

.row
  .col-12.col-md-6.offset-md-3
    - if @items.blank?
      .alert.alert-primary No items yet
    - else
      .list-group
        = render @items

app/views/items/new.html.haml
- if @item
  = render partial: 'form', locals: { title: 'New item'}

app/views/items/show.html.haml
.row
  .col-12
    = render partial: 'model_errors', locals: { item: @item }
  .col-12.col-md-4
    = render partial: 'item_details', locals: { item: @item}
  .col-12.col-md-4
    = render partial: 'move_form', locals: { item: @item }
  .col-12.col-md-4
    = render partial: 'move_all_form', locals: { item: @item }

app/views/items/warehouse.html.haml
%h1.text-center.mb-4.mt-4="Warehouse #{@name}"
.text-center
  = link_to "Close warehouse", warehouse_path(@name), method: "delete", class: "btn btn-danger mb-4", data: { confirm: "All stock in this warehouse will be deleted" }
.row
  .col-12.col-md-6.offset-md-3
    - if @items.blank?
      .alert.alert-primary No items in this warehouse
    - else
      .list-group
        = render @items

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: flash_class(key), role: "alert"}
    = value
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand.navbar-light.bg-light
  = link_to 'Stock manager', root_path, class: 'navbar-brand'
  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      %li.navbar-item
        = link_to 'All items', items_path, class: "nav-link"
  = link_to 'New item', new_item_path, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, user-scalable=no", :name => "viewport"}/
    %title Stock manager
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      = yield